### ISSUE TITLE
Failed to write and RAM consumption

### ISSUE THREAD

**Issue by liquidcol** [matiascodesal/maya-glTF#15]
This plugin makes excessive consumption of RAM, I tested in Maya 2019.2 on Mac and a PC and has the same problem, and basically it is processed when exporting ....... In the end I see this error ...

# Failed to write file information
// Error: line 0: MemoryError: file H: / WS / My Documents / maya / 2019 / scripts \ glTFExport.py line 474: //
// Error: line 0: Could not save file "H: /Maya/default/scenes/file.glb". //

**Comment by PeterTucker** [comment]
Bump. The same happens to me. I'm using Maya 2019. Memory consumption hovers around 96%... Doesn't look to be writing anything. It's been exporting for around 5 minutes now. Going to give it 5 more minutes.

**Comment by kyndred** [comment]
Same results in 2020.2
Seems to work in 2018.7

**Comment by gregottoniemeyer** [comment]
Not working in Maya 2020... please update if possible.

**Comment by matiascodesal** [comment]
Thanks for reporting and sorry for the delay.  This plugins fallen by the wayside since I'm not using it in my daily work anymore.  Looks like something changed in the Maya API for 2019+.  The hang from trying to convert an MPoint to a Python List which worked in <=2018 😞 
```list(boundingBox.max())```

I just pushed the fix if you want to try again.  Please reopen if there's still an issue.
