### ISSUE TITLE
Differences or direction compared to Maya2glTF plugin?

### ISSUE THREAD

**Issue by donmccurdy** [matiascodesal/maya-glTF#7]
Hi @matiascodesal — Thanks for posting this plugin, it's awesome to see work toward glTF support in Maya. Quick question: have you seen https://github.com/Ziriax/Maya2glTF, which looks to me like a similar effort? I'm wondering if there are important differences between these (C++ vs Python would be one I imagine).

**Comment by matiascodesal** [comment]
@donmccurdy At this point, I'd recommend folks just use Ziriax's plugin.  Maya2glTF was lacking a lot of features that I needed when I started maya-glTF.  The only real advantage to mine now is that it's practically  platform and Maya version independent since there are no binaries that need to be built.

**Comment by donmccurdy** [comment]
Ok that is helpful to know, thank you for clarifying! 🙂
